Lecture 4/hw
Charl1eV/react-20240513 pull request #4
Opened 2024-05-29 17:09 UTC by Charl1eV

2024-05-30 15:49 UTC, SArchieEdu requested changes

2024-05-30 15:49 UTC, SArchieEdu commented on src/components/scroll-progress-bar/component.jsx
> +    window.addEventListener("scroll", setScrollWidth);
на лекции рассказывал про работу с дом элементами. Необходимо использовать useEffect
И нужно не забывать отписываться

2024-05-30 15:49 UTC, SArchieEdu commented on src/components/rating/component.jsx
> +export const Rating = ({ min, max, rating, dispatch }) => {
этому компоненту не нужно знать что используется в родителе, а dispatch  это завязка на реализацию. onChange gjljqltn kexit

2024-05-30 15:49 UTC, SArchieEdu commented on src/components/rating/component.jsx
> +                    <button onClick={() => dispatch({ type: "setRating", payload: index + 1 })} disabled={rating === index + 1}>{index + 1}</button>
этот компонент не будет работать если в родителе будет useState

2024-05-31 08:37 UTC, Charl1eV commented on src/components/scroll-progress-bar/component.jsx
> +    window.addEventListener("scroll", setScrollWidth);
Поправила

2024-05-31 10:33 UTC, merged